### ISSUE TITLE
Question about tailwindui

### ISSUE THREAD

**Issue by IndependentCreator** [hellotham/hello-astro#15]
Hi Christine,

I'm still learning about Astro and Tailwind and I noticed that you mention TailwindUI in the README.md. I was looking into tailwindui.com and reading about their [licenses](https://tailwindui.com/license), but I'm not sure exactly how/if hello-astro uses tailwindui. Do you know if there are any licensing issues related to tailwindui that would affect users of hello-astro?

Another option I'm looking into is building something similar using https://daisyui.com/, since it uses the MIT license. If I wanted to do that, would I need to replace the contents of components/ with similar components from daisyui?

Thanks for any guidance you can provide and for sharing such a beautiful theme with us!

**Comment by ChristineTham** [comment]
> 



> I'm not sure exactly how/if hello-astro uses tailwindui. Do you know if there are any licensing issues related to tailwindui that would affect users of hello-astro?

Hello

hello-astro only uses the "free" components provided as a preview in this link:
https://tailwindui.com/components/preview

I don't think there should be any licensing issues as the source code of these components are provided as a "sampler" for tailwindui. hello-astro does not use any of the "paid" components. In any case, these components were not used "as is" but were modified (for example, AlpineJS is used for interactivity rather than HeadlessUI).

**Comment by IndependentCreator** [comment]
Got it, thanks for clarifying!
