### ISSUE TITLE
PhotoSwipe is broken

### ISSUE THREAD

**Issue by snoopy21** [hellotham/hello-astro#9]
Since the last update, photos in a gallery are opening as @astroimage and not in a lightbox.

**Comment by ChristineTham** [comment]
Hi, thanks for raising this issue.

This appears to be due to a bug in Astro v2.x - hoisted scripts and full resolution images do not respect the base configuration property which is used in this starter to generate the demo site.

Until Astro fixes this issue, a workaround is to comment out or delete the base configuration option in `astro.config.mjs`

I know this is not ideal if you do need to set base. I will issue a new release once this problem is fixed in Astro.

**Comment by snoopy21** [comment]
Hi, thanks for you response

I tried it out and it seems Astro fixed this issue.
